### PR TITLE
Ensure 'checkstyleNohttp' task is cacheable

### PR DESCRIPTION
**Pull request by facewindu**
by writing relative paths to 'configProperties' input properties, instead of absolute paths

### CODE REVIEW

**Comment by wilkinsona** [comment]
LGTM. Thank you, @facewindu.

**Comment by rwinch** [comment]
Thanks for the PR @facewindu!

I'd like to get a test to verify that up to date works going forward. I added [an up to date test](https://github.com/rwinch/nohttp/commit/04e298a5113e4f0c0fd3e33805afe669958a693d#diff-d68385789dbddfbcc12eb145b4fc3555R63-R73) that does not change the directories and it works fine. However, I [attempted to add one](https://github.com/rwinch/nohttp/commit/04e298a5113e4f0c0fd3e33805afe669958a693d#diff-d68385789dbddfbcc12eb145b4fc3555R75-R87) for when the directories change, but the build appears to run again. Any ideas on what is happening?

**Comment by facewindu** [comment]
@rwinch 
Your 'up-to-date relocated' build cannot work, as absolute paths to the file outputs are used for incremental build. Said differently, incremental build can only work within the same directory. (And your first test shows that it works).
I made a few changes to
- add test coverage when using the build cache and relocated builds
- changed the output location of the `checkstyleNohttp` task to be on its own directory (not the one based on the sub-classed checkstyle class), in order not to have overlapping outputs, if a build uses `checkstyle` and `checkstyleNoHttp`.

**Comment by rwinch** [comment]
Thanks for the additional details. 

> incremental build can only work within the same directory

1) What do we gain by doing relative paths if the build can only work within the same directory?

2) This sounds like the originally reported issue cannot be solved then? The [original issue stated](https://github.com/spring-io/nohttp/issues/31#issue-521506358):

> When a build for the same commit is run from two different locations on the file system (as happens when running on CI and then on a developer's machine), the checkstyleNoHttp task is not cacheable due to two differences in its inputs

**Comment by facewindu** [comment]
> 1. What do we gain by doing relative paths if the build can only work within the same directory?

Incremental build means using up-to-date-checks. Which are local to the project directory.
It's not at all the same as using a local/remote build cache.
In this regard, caching is more powerful.

> 2. This sounds like the originally reported issue cannot be solved then? The [original issue stated](https://github.com/spring-io/nohttp/issues/31#issue-521506358):
> > When a build for the same commit is run from two different locations on the file system (as happens when running on CI and then on a developer's machine), the checkstyleNoHttp task is not cacheable due to two differences in its inputs

Related to one. Now the `checkstyleNoHttp` task is _cacheable_, which is not the same as _incremental_. It can now be safely reused across build locations (locally, and even on other machines (developer machines and/or CI nodes) thanks to using build caching.

See for instance [this section](https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_intro) of the userguide for clearer explanations.

**Comment by rwinch** [comment]
Thanks for the additional details @facewindu! This is now merged into master

**Comment by etiennestuder** [comment]
Cool. Looking forward to the Spring Framework build benefiting from this fix once a new version of the plugin is released.

**Pull request merged**
